### ISSUE TITLE
Any idea on how to get it to work on Debian / Ubuntu

### ISSUE THREAD

**Issue by hashhar** [axper/man2archwiki#1]

**Comment by axper** [comment]
Install arch linux!

Just kidding, post the error message.

**Comment by hashhar** [comment]
Well, it was mainly the trouble I had in finding the mdocml / mandoc debian packages. I got it working now. It's beautiful. Is there any way I could limit the width of the resulting page. It's a bit too wide for my taste. I'll try seeing the script's source.
